export const technologies: string[] = [
    "Django",
    "Next.js",
    "Nodejs",
    "Laravel",
    ".NET",
    "Angular",
    "Alpinejs",
    "Tailwind",
    "PostgreSQL",
    "MongoDB",
    "GIT",
    "Docker",
    "Kubernetes",
    "Google Cloud",
    "AWS",
    "Wordpress",
    "Shopify",
    "Bigcommerce",
    "Stripe",
    "Paypal",
    "Photoshop",
    "Illustrator",
    "Figma",
];
